name: Check ESPHome YAML output
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  check-output:
    name: Verify YAML output
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: python3 -m upk2esphome.test
